server:
  port: 8081

spring:
  application:
    name: SyncPhotos
  datasource:
#    data: classpath:data.sql
    driver-class-name: org.h2.Driver
    password: ''
    schema: classpath:schema.sql
    url: jdbc:h2:file:~/SyncPhotos-db
    username: san
  mvc:
    static-path-pattern: /res/**
  resources:
    static-locations: file:/Users/liuxuyang/IdeaProjects/SyncPhotos/target/classes/SyncPhotos

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**.xml
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0